"""Framework-neutral algorithm control-plane contracts."""

from tributo.algorithms.api import (
    AlgorithmExecutionResult,
    AlgorithmOperation,
    AlgorithmRegistration,
    AlgorithmRequest,
    AlgorithmRunResult,
    ArtifactDraft,
    BackendInputCompatibility,
    CollectivePolicy,
    DistributedAlgorithmDescriptor,
    DistributionSpec,
    DistributionStrategy,
    EnvironmentSpec,
    ExecutionMode,
    ExecutionProfile,
    ExecutionReceipt,
    ExecutionRequest,
    FrameworkNativePolicy,
    ImplementationDescriptor,
    InputBinding,
    InputDistribution,
    MapReducePolicy,
    MetricReduction,
    QualifiedReference,
    ResultPolicy,
    RuntimeBinding,
    RuntimeTopology,
    StateCoordination,
    StateCoordinationEvidence,
    StateField,
    UserExecutionContext,
    WorkerExecutionEvidence,
    WorkerRange,
    WorkerResources,
)
from tributo.algorithms.composition import build_algorithm_dispatcher
from tributo.algorithms.core.builder import AlgorithmBuilder

__all__ = [
    "AlgorithmExecutionResult",
    "AlgorithmBuilder",
    "AlgorithmOperation",
    "AlgorithmRegistration",
    "AlgorithmRequest",
    "AlgorithmRunResult",
    "ArtifactDraft",
    "BackendInputCompatibility",
    "CollectivePolicy",
    "DistributionSpec",
    "DistributedAlgorithmDescriptor",
    "DistributionStrategy",
    "EnvironmentSpec",
    "ExecutionMode",
    "ExecutionProfile",
    "ExecutionReceipt",
    "ExecutionRequest",
    "FrameworkNativePolicy",
    "ImplementationDescriptor",
    "InputDistribution",
    "InputBinding",
    "MapReducePolicy",
    "MetricReduction",
    "QualifiedReference",
    "ResultPolicy",
    "RuntimeBinding",
    "RuntimeTopology",
    "StateCoordination",
    "StateCoordinationEvidence",
    "StateField",
    "UserExecutionContext",
    "WorkerExecutionEvidence",
    "WorkerRange",
    "WorkerResources",
    "build_algorithm_dispatcher",
]
