"""Ray Tune hyperparameter tuning runner.

Adapts Tributo's TrainerSpec to Ray Tune's trainable,
supporting JSON search space configuration and multiple search algorithms/schedulers.
"""

from __future__ import annotations

import logging
from typing import Any, Callable

import ray
import ray.data
from ray.tune import ResultGrid, RunConfig, Tuner
from ray.tune.schedulers import ASHAScheduler, FIFOScheduler, HyperBandScheduler
from ray.tune.search import BasicVariantGenerator

from tributo.exceptions import JobConfigurationError, JobExecutionError
from tributo.training.registry import TrainerSpec
from tributo.training.tune_config import TuneSearchConfig
from tributo.util.annotations import PublicAPI

logger = logging.getLogger(__name__)

# Scheduler mapping (lazy instantiation to avoid unnecessary imports)
_SCHEDULER_MAP: dict[str, Any] = {
    "fifo": lambda metric, mode: FIFOScheduler(),
    "asha": lambda metric, mode: ASHAScheduler(metric=metric, mode=mode),
    "hyperband": lambda metric, mode: HyperBandScheduler(metric=metric, mode=mode),
}

# Search algorithm mapping (lazy instantiation)
_SEARCH_ALG_MAP: dict[str, Any] = {
    "random": lambda metric, mode: BasicVariantGenerator(),
}


def _get_bayesopt_search(metric: str, mode: str) -> Any:
    """Get a BayesOpt search algorithm instance (optional dependency)."""
    try:
        from ray.tune.search.bayesopt import BayesOptSearch

        return BayesOptSearch(metric=metric, mode=mode)
    except ImportError as err:
        raise ImportError(
            "bayesian-optimization is required for BayesOpt search algorithm. "
            "Install with: pip install bayesian-optimization"
        ) from err


_SEARCH_ALG_MAP["bayesopt"] = _get_bayesopt_search


@PublicAPI(stability="beta")
class TuneRunner:
    """Ray Tune hyperparameter tuning runner.

    Adapts Tributo's TrainerSpec to Ray Tune's trainable,
    supporting JSON search space configuration and multiple search algorithms/schedulers.

    Example:
        >>> from tributo.training.registry import get_trainer
        >>> from tributo.training.tune_config import TuneSearchConfig
        >>> from tributo.training.tune_space import parse_search_space
        >>> from tributo.training.tune_runner import TuneRunner
        >>>
        >>> trainer_spec = get_trainer("xgboost")
        >>> search_space = parse_search_space("space.json")
        >>> tune_config = TuneSearchConfig(num_samples=10, search_alg="random")
        >>> runner = TuneRunner(trainer_spec, tune_config, search_space)
        >>> result_grid = runner.run(datasets={"train": ds}, output_path="/tmp/out")
    """

    def __init__(
        self,
        trainer_spec: TrainerSpec,
        tune_config: TuneSearchConfig,
        search_space: dict[str, Any],
    ):
        """Initialize TuneRunner.

        Args:
            trainer_spec: Trainer registration specification.
            tune_config: Search configuration (algorithm, scheduler, sampling count, etc.).
            search_space: Ray Tune param_space dictionary (generated by parse_search_space).

        Raises:
            JobConfigurationError: Unsupported search algorithm or scheduler.
        """
        self._trainer_spec = trainer_spec
        self._tune_config = tune_config
        self._search_space = search_space

        # Instantiate search algorithm and scheduler early to detect missing optional dependencies
        # (e.g., uninstalled BayesOpt will throw ImportError immediately)
        try:
            search_alg_factory = _SEARCH_ALG_MAP[tune_config.search_alg]
            scheduler_factory = _SCHEDULER_MAP[tune_config.scheduler]
        except KeyError as exc:
            raise JobConfigurationError(
                f"Unsupported search_alg='{tune_config.search_alg}' "
                f"or scheduler='{tune_config.scheduler}'"
            ) from exc
        self._search_alg = search_alg_factory(
            tune_config.metric,
            tune_config.mode,
        )
        self._scheduler = scheduler_factory(
            tune_config.metric,
            tune_config.mode,
        )

    def _build_trainable(
        self,
        datasets: dict[str, ray.data.Dataset],
        output_path: str,
    ) -> Callable[[dict[str, Any]], None]:
        """Convert TrainerSpec to a Ray Tune trainable function.

        Uses a closure to capture datasets and output_path, avoiding injection
        of non-hyperparameter data into param_space (Ray Tune tries to sample all keys in param_space).

        Args:
            datasets: Dataset dictionary (bound via closure, not entered into param_space).
            output_path: Output path (bound via closure, not entered into param_space).

        Returns:
            Ray Tune trainable function.
        """
        trainer_cls = self._trainer_spec.trainer_cls
        default_config = self._trainer_spec.default_config

        def trainable(config: dict[str, Any]) -> None:
            """Ray Tune trainable function.

            Args:
                config: Hyperparameters injected by Ray Tune (sampled from search space).
                    Contains only hyperparameters defined in the search space, not datasets/output_path.
            """
            from ray import tune as ray_tune

            # Merge default config with search space samples
            merged_config = {**default_config, **config}

            # Instantiate trainer and execute (datasets and output_path captured via closure)
            trainer = trainer_cls(
                datasets=datasets,
                config=merged_config,
            )
            try:
                summary = trainer.run(output_path=output_path)
            except Exception as exc:
                logger.exception(
                    "Trial failed with config: %s",
                    config,
                )
                raise JobExecutionError(
                    f"Trial failed for trainer '{trainer_cls.__name__}'"
                ) from exc

            # Report metrics to Ray Tune
            # Support nested metric structures (e.g., XGBoostTrainer's summary["metrics"])
            metrics = {}
            for k, v in summary.items():
                if isinstance(v, (int, float)):
                    metrics[k] = v
                elif isinstance(v, dict) and k == "metrics":
                    # Extract nested metrics dictionary
                    for mk, mv in v.items():
                        if isinstance(mv, (int, float)):
                            metrics[mk] = mv

            if not metrics:
                raise JobExecutionError(
                    f"Trainer '{trainer_cls.__name__}' returned no numeric metrics. "
                    "Tune requires at least one numeric metric to optimize."
                )

            ray_tune.report(metrics)

        return trainable

    def _build_tune_config(self) -> Any:
        """Build the Ray Tune TuneConfig object.

        Returns:
            ray.tune.TuneConfig instance.
        """
        from ray.tune import TuneConfig

        return TuneConfig(
            metric=self._tune_config.metric,
            mode=self._tune_config.mode,
            num_samples=self._tune_config.num_samples,
            max_concurrent_trials=self._tune_config.max_concurrent_trials,
            time_budget_s=self._tune_config.time_budget_s,
            search_alg=self._search_alg,
            scheduler=self._scheduler,
        )

    def _build_failure_config(self) -> Any:  # type: ignore[no-untyped-def]
        """Build the failure configuration.

        Returns:
            ray.tune.FailureConfig instance.
        """
        from ray.tune import FailureConfig

        return FailureConfig(
            fail_fast=self._tune_config.fail_fast,
        )

    def run(
        self,
        datasets: dict[str, ray.data.Dataset],
        output_path: str,
        experiment_name: str = "tributo-tune",
        runtime_env: dict[str, Any] | None = None,
    ) -> ResultGrid:
        """Execute hyperparameter search.

        Args:
            datasets: Dataset dictionary (e.g. {"train": ds}).
            output_path: Output path (local or S3).
            experiment_name: Experiment name.
            runtime_env: Optional Ray runtime environment for Tune trial workers.
                In Ray Tune v1, this is set at the Ray session level and
                inherited by all trial actors. If Ray has not been initialized
                when this method is called, ``ray.init(runtime_env=runtime_env)``
                is called automatically. If Ray is already initialized, a
                warning is logged — set ``runtime_env`` at ``ray.init()`` before
                creating the ``TuneRunner`` instead.
                Example: ``{"pip": ["xgboost"]}`` to install optional extras.

        Returns:
            Ray Tune ResultGrid containing all trial results.
        """
        # Set runtime_env at Ray session level (only before ray.init)
        if runtime_env is not None:
            if not ray.is_initialized():
                ray.init(runtime_env=runtime_env)
            else:
                logger.warning(
                    "runtime_env=%s provided but Ray is already initialized. "
                    "Set runtime_env at ray.init() before creating TuneRunner.",
                    runtime_env,
                )

        # Capture datasets and output_path via closure, not injected into param_space
        trainable = self._build_trainable(datasets, output_path)

        tuner = Tuner(
            trainable=trainable,
            param_space=self._search_space,  # contains only search space hyperparameters
            tune_config=self._build_tune_config(),
            run_config=RunConfig(
                name=experiment_name,
                storage_path=output_path,
                failure_config=self._build_failure_config(),
            ),
        )

        logger.info(
            "Starting Tune experiment '%s': %d samples, %s algorithm, %s scheduler",
            experiment_name,
            self._tune_config.num_samples,
            self._tune_config.search_alg,
            self._tune_config.scheduler,
        )

        result_grid = tuner.fit()

        # Output result summary
        try:
            best_result = result_grid.get_best_result()
        except RuntimeError as exc:
            raise JobExecutionError(
                f"Tune experiment failed to find best result for metric="
                f"'{self._tune_config.metric}', mode='{self._tune_config.mode}'. "
                "This usually means all trials failed or no trial reported the metric."
            ) from exc
        metric_value = (
            best_result.metrics.get(self._tune_config.metric, float("nan"))
            if best_result.metrics
            else float("nan")
        )
        logger.info(
            "Best trial: metric=%s=%.4f",
            self._tune_config.metric,
            metric_value,
        )

        # Persist experiment summary
        self._save_summary(result_grid, output_path, experiment_name)

        return result_grid

    def _save_summary(
        self,
        result_grid: ResultGrid,
        output_path: str,
        experiment_name: str,
    ) -> None:
        """Save experiment summary to output path.

        Args:
            result_grid: Tune experiment results.
            output_path: Output path (local directory or S3 URI).
            experiment_name: Experiment name.
        """
        try:
            best_params = extract_best_params(
                result_grid,
                metric=self._tune_config.metric,
                mode=self._tune_config.mode,
            )
            summary = {
                "experiment_name": experiment_name,
                "metric": self._tune_config.metric,
                "mode": self._tune_config.mode,
                "num_samples": self._tune_config.num_samples,
                "search_alg": self._tune_config.search_alg,
                "scheduler": self._tune_config.scheduler,
                "best_params": best_params,
                "num_trials": len(result_grid),
                "num_errors": result_grid.num_errors,
            }

            from tributo._common.storage import write_json

            summary_path = output_path.rstrip("/") + "/tune_summary.json"
            write_json(summary_path, summary)
            logger.info("Tune summary saved to %s", summary_path)
        except Exception:
            logger.exception("Failed to save tune summary, continuing")


@PublicAPI(stability="beta")
def extract_best_params(
    result_grid: ResultGrid,
    metric: str = "loss",
    mode: str = "min",
) -> dict[str, Any]:
    """Extract the best trial's hyperparameters from a ResultGrid.

    Args:
        result_grid: Return value of TuneRunner.run().
        metric: Optimization metric name.
        mode: Optimization direction (min/max).

    Returns:
        Hyperparameter dictionary of the best trial.

    Raises:
        JobExecutionError: When the best trial has no available configuration.
    """
    try:
        best_result = result_grid.get_best_result(metric=metric, mode=mode)
    except RuntimeError as exc:
        raise JobExecutionError(
            f"No best result found for metric='{metric}', mode='{mode}'. "
            "This usually means all trials failed or no trial reported the metric."
        ) from exc
    if best_result.config is None:
        raise JobExecutionError(
            f"No valid config found in best result for metric={metric}, mode={mode}"
        )
    return best_result.config
