"""Public alpha contracts for portable algorithm execution."""

from tributo.algorithms.api.context import UserExecutionContext
from tributo.algorithms.api.errors import (
    AlgorithmConfigurationError,
    AlgorithmDependencyError,
    AlgorithmExecutionError,
    AlgorithmInputError,
    AlgorithmResolutionError,
)
from tributo.algorithms.api.models import (
    AlgorithmExecutionResult,
    AlgorithmOperation,
    AlgorithmRegistration,
    AlgorithmRequest,
    AlgorithmResolution,
    AlgorithmRunResult,
    ArtifactDraft,
    BackendInputCompatibility,
    EnvironmentSpec,
    ExecutionMode,
    FailureCategory,
    ImplementationDescriptor,
    InputBinding,
    QualifiedReference,
    ResolvedAlgorithmPlan,
    ResolvedInputDescriptor,
    RuntimeBinding,
    RuntimeTopology,
    WorkerExecutionResult,
    canonical_digest,
)

__all__ = [
    "AlgorithmConfigurationError",
    "AlgorithmDependencyError",
    "AlgorithmExecutionError",
    "AlgorithmExecutionResult",
    "AlgorithmInputError",
    "AlgorithmOperation",
    "AlgorithmRegistration",
    "AlgorithmRequest",
    "AlgorithmResolution",
    "AlgorithmResolutionError",
    "AlgorithmRunResult",
    "ArtifactDraft",
    "BackendInputCompatibility",
    "EnvironmentSpec",
    "ExecutionMode",
    "FailureCategory",
    "ImplementationDescriptor",
    "InputBinding",
    "QualifiedReference",
    "ResolvedAlgorithmPlan",
    "ResolvedInputDescriptor",
    "RuntimeBinding",
    "RuntimeTopology",
    "UserExecutionContext",
    "WorkerExecutionResult",
    "canonical_digest",
]
