"""Public alpha contracts for portable algorithm execution."""

from tributo.algorithms.api.context import UserExecutionContext
from tributo.algorithms.api.descriptor import DistributedAlgorithmDescriptor
from tributo.algorithms.api.distribution import (
    CollectivePolicy,
    DistributionSpec,
    DistributionStrategy,
    ExecutionProfile,
    FrameworkNativePolicy,
    InputDistribution,
    MapReducePolicy,
    MetricReduction,
    ResultPolicy,
    StateCoordination,
    StateField,
    WorkerRange,
    WorkerResources,
)
from tributo.algorithms.api.errors import (
    AlgorithmConfigurationError,
    AlgorithmDependencyError,
    AlgorithmExecutionError,
    AlgorithmInputError,
    AlgorithmResolutionError,
)
from tributo.algorithms.api.execution import (
    ExecutionReceipt,
    ExecutionRequest,
    StateCoordinationEvidence,
    WorkerExecutionEvidence,
)
from tributo.algorithms.api.models import (
    AlgorithmExecutionResult,
    AlgorithmOperation,
    AlgorithmRegistration,
    AlgorithmRequest,
    AlgorithmResolution,
    AlgorithmRunResult,
    ArtifactDraft,
    BackendInputCompatibility,
    EnvironmentSpec,
    ExecutionMode,
    FailureCategory,
    ImplementationDescriptor,
    InputBinding,
    QualifiedReference,
    ResolvedAlgorithmPlan,
    ResolvedInputDescriptor,
    RuntimeBinding,
    RuntimeTopology,
    WorkerExecutionResult,
    canonical_digest,
)

__all__ = [
    "AlgorithmConfigurationError",
    "AlgorithmDependencyError",
    "AlgorithmExecutionError",
    "AlgorithmExecutionResult",
    "AlgorithmInputError",
    "AlgorithmOperation",
    "AlgorithmRegistration",
    "AlgorithmRequest",
    "AlgorithmResolution",
    "AlgorithmResolutionError",
    "AlgorithmRunResult",
    "ArtifactDraft",
    "BackendInputCompatibility",
    "CollectivePolicy",
    "DistributionSpec",
    "DistributedAlgorithmDescriptor",
    "DistributionStrategy",
    "EnvironmentSpec",
    "ExecutionMode",
    "ExecutionProfile",
    "ExecutionReceipt",
    "ExecutionRequest",
    "FailureCategory",
    "FrameworkNativePolicy",
    "ImplementationDescriptor",
    "InputDistribution",
    "InputBinding",
    "MapReducePolicy",
    "MetricReduction",
    "QualifiedReference",
    "ResolvedAlgorithmPlan",
    "ResolvedInputDescriptor",
    "RuntimeBinding",
    "RuntimeTopology",
    "ResultPolicy",
    "StateCoordination",
    "StateCoordinationEvidence",
    "StateField",
    "UserExecutionContext",
    "WorkerExecutionEvidence",
    "WorkerExecutionResult",
    "WorkerRange",
    "WorkerResources",
    "canonical_digest",
]
