name: Feature request
description: Suggest an idea for Tributo
title: "[<Tributo component: Core|Training|Data|Exporting|Registry|Inference|Serving|Integrations|CLI|Docs|etc...>] "
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to propose a new feature!
        We appreciate your contribution to Tributo.

  - type: textarea
    attributes:
      label: Description
      description: A short description of the feature.
      placeholder: What should Tributo support?

  - type: textarea
    attributes:
      label: Use case
      description: Describe the use case for this feature. It will help us understand and prioritize the request.
      placeholder: Rather than focusing on implementation details, describe what you are trying to accomplish.
