"""Provisional extension protocols for portable algorithms."""

from tributo.algorithms.spi.contracts import AlgorithmContractValidator
from tributo.algorithms.spi.execution import (
    AlgorithmExecutionContext,
    CollectiveAlgorithm,
    EnsembleUnitSpec,
    Evaluable,
    ExecutionEnvelope,
    Fittable,
    FrameworkNativeAlgorithm,
    IterativeOptimizationAlgorithm,
    JoblibEstimatorRecipe,
    MapReduceAlgorithm,
    ParallelEnsembleAlgorithm,
    PortableRuntimeAdapter,
    Predictable,
    RuntimeExecutionEnvelope,
    Transformable,
)
from tributo.algorithms.spi.input import (
    InputExecutionContext,
    InputResolutionContext,
    InputResolverPort,
    InputRuntimeAdapter,
    MaterializedTabularInputView,
    PreparedInput,
    ResolvedInputLease,
    RuntimeInputBinding,
    TabularBatchInputView,
    WorkerInputAdapter,
    WorkerInputPayload,
    WorkerInputPayloadSet,
)
from tributo.algorithms.spi.torch import (
    MetricPlan,
    OptimizationPlan,
    TorchTrainingRecipe,
    TrainingRecipeV2,
    TrainingStepResult,
)

__all__ = [
    "AlgorithmContractValidator",
    "AlgorithmExecutionContext",
    "CollectiveAlgorithm",
    "EnsembleUnitSpec",
    "Evaluable",
    "ExecutionEnvelope",
    "Fittable",
    "FrameworkNativeAlgorithm",
    "IterativeOptimizationAlgorithm",
    "JoblibEstimatorRecipe",
    "InputExecutionContext",
    "InputResolutionContext",
    "InputResolverPort",
    "InputRuntimeAdapter",
    "MaterializedTabularInputView",
    "MapReduceAlgorithm",
    "MetricPlan",
    "OptimizationPlan",
    "ParallelEnsembleAlgorithm",
    "PortableRuntimeAdapter",
    "Predictable",
    "RuntimeExecutionEnvelope",
    "PreparedInput",
    "ResolvedInputLease",
    "RuntimeInputBinding",
    "TabularBatchInputView",
    "Transformable",
    "TorchTrainingRecipe",
    "TrainingRecipeV2",
    "TrainingStepResult",
    "WorkerInputAdapter",
    "WorkerInputPayload",
    "WorkerInputPayloadSet",
]
