"""Provisional extension protocols for portable algorithms."""

from tributo.algorithms.spi.execution import (
    AlgorithmExecutionContext,
    CollectiveAlgorithm,
    Evaluable,
    ExecutionEnvelope,
    Fittable,
    FrameworkNativeAlgorithm,
    MapReduceAlgorithm,
    PortableRuntimeAdapter,
    Predictable,
    RuntimeExecutionEnvelope,
    Transformable,
)
from tributo.algorithms.spi.input import (
    InputExecutionContext,
    InputResolutionContext,
    InputResolverPort,
    InputRuntimeAdapter,
    MaterializedTabularInputView,
    PreparedInput,
    ResolvedInputLease,
    RuntimeInputBinding,
    TabularBatchInputView,
    WorkerInputAdapter,
    WorkerInputPayload,
)

__all__ = [
    "AlgorithmExecutionContext",
    "CollectiveAlgorithm",
    "Evaluable",
    "ExecutionEnvelope",
    "Fittable",
    "FrameworkNativeAlgorithm",
    "InputExecutionContext",
    "InputResolutionContext",
    "InputResolverPort",
    "InputRuntimeAdapter",
    "MaterializedTabularInputView",
    "MapReduceAlgorithm",
    "PortableRuntimeAdapter",
    "Predictable",
    "RuntimeExecutionEnvelope",
    "PreparedInput",
    "ResolvedInputLease",
    "RuntimeInputBinding",
    "TabularBatchInputView",
    "Transformable",
    "WorkerInputAdapter",
    "WorkerInputPayload",
]
