"""Generate the registered-algorithm region of the support matrix."""

from __future__ import annotations

import argparse
import html
import sys
from pathlib import Path
from typing import TYPE_CHECKING, Sequence

if TYPE_CHECKING:
    from tributo.training.support_snapshot import AlgorithmSupportRecord

REPOSITORY_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_SUPPORT_MATRIX = REPOSITORY_ROOT / "docs" / "reference" / "support-matrix.md"

BEGIN_MARKER = "<!-- BEGIN GENERATED: TRIBUTO ALGORITHM SUPPORT -->"
END_MARKER = "<!-- END GENERATED: TRIBUTO ALGORITHM SUPPORT -->"


class SupportMatrixGenerationError(ValueError):
    """The generated region cannot be located without ambiguity."""


def load_support_snapshot() -> tuple[AlgorithmSupportRecord, ...]:
    """Load registered support facts without importing frameworks directly."""
    from tributo.training.catalog import get_algorithm_catalog
    from tributo.training.support_snapshot import build_algorithm_support_snapshot

    return build_algorithm_support_snapshot(get_algorithm_catalog().list_records())


def _code(value: str) -> str:
    """Render an untrusted Registry value safely inside a Markdown table."""
    escaped = html.escape(value, quote=True).replace("|", "&#124;")
    return f"<code>{escaped}</code>"


def _values(values: Sequence[str]) -> str:
    """Render a sequence while preserving the Registry-declared order."""
    return ", ".join(_code(value) for value in values) if values else "—"


def render_generated_region(snapshot: Sequence[AlgorithmSupportRecord]) -> str:
    """Render the complete marker-delimited registered-algorithm region."""
    lines = [
        BEGIN_MARKER,
        "<!-- Generated by tools/generate_algorithm_support_matrix.py; do not edit. -->",
        "| Algorithm | Lifecycle | Stability | Availability | Tested | Supported | Execution | Implementations | Topology | Input views | Limitations |",
        "| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    lines.extend(
        "| "
        + " | ".join(
            (
                _code(record.name),
                _code(record.status),
                _code(record.stability),
                _code(
                    "compatibility-only"
                    if record.compatibility_only
                    else ("available" if record.available else "unavailable")
                ),
                _code("yes" if record.tested else "no"),
                _code("yes" if record.supported else "no"),
                _values(record.supported_tasks),
                _values(record.implementation_ids),
                _values(record.runtime_topologies),
                _values(record.input_views),
                _values(record.limitations),
            )
        )
        + " |"
        for record in snapshot
    )
    lines.append(END_MARKER)
    return "\n".join(lines)


def replace_generated_region(
    document: str,
    snapshot: Sequence[AlgorithmSupportRecord],
) -> str:
    """Replace exactly one generated region and preserve all manual prose."""
    begin_count = document.count(BEGIN_MARKER)
    end_count = document.count(END_MARKER)
    if begin_count != 1 or end_count != 1:
        raise SupportMatrixGenerationError(
            "support matrix must contain exactly one begin marker and one end "
            f"marker; found begin={begin_count}, end={end_count}"
        )

    begin = document.index(BEGIN_MARKER)
    end_start = document.index(END_MARKER)
    if end_start < begin:
        raise SupportMatrixGenerationError(
            "support matrix end marker appears before begin marker"
        )
    end = end_start + len(END_MARKER)
    return document[:begin] + render_generated_region(snapshot) + document[end:]


def check_support_matrix(
    path: Path,
    snapshot: Sequence[AlgorithmSupportRecord] | None = None,
) -> list[str]:
    """Return validation errors without modifying *path*."""
    current = path.read_text(encoding="utf-8")
    marker_errors = _marker_structure_errors(path, current)
    if marker_errors:
        return marker_errors
    try:
        resolved_snapshot = load_support_snapshot() if snapshot is None else snapshot
        expected = replace_generated_region(current, resolved_snapshot)
    except SupportMatrixGenerationError as exc:
        return [f"{path}: {exc}"]
    if current != expected:
        return [
            f"{path}: generated algorithm support region is stale; "
            "run tools/generate_algorithm_support_matrix.py"
        ]
    return []


def validate_marker_structure(path: Path) -> list[str]:
    """Validate marker uniqueness without loading the algorithm catalog."""
    document = path.read_text(encoding="utf-8")
    return _marker_structure_errors(path, document)


def _marker_structure_errors(path: Path, document: str) -> list[str]:
    """Validate marker structure in one immutable document read."""
    begin_count = document.count(BEGIN_MARKER)
    end_count = document.count(END_MARKER)
    if begin_count != 1 or end_count != 1:
        return [
            f"{path}: support matrix must contain exactly one begin marker and "
            f"one end marker; found begin={begin_count}, end={end_count}"
        ]
    if document.index(END_MARKER) < document.index(BEGIN_MARKER):
        return [f"{path}: support matrix end marker appears before begin marker"]
    return []


def write_support_matrix(
    path: Path,
    snapshot: Sequence[AlgorithmSupportRecord] | None = None,
) -> bool:
    """Update only the generated region and return whether the file changed."""
    current = path.read_text(encoding="utf-8")
    resolved_snapshot = load_support_snapshot() if snapshot is None else snapshot
    updated = replace_generated_region(current, resolved_snapshot)
    if updated == current:
        return False
    path.write_text(updated, encoding="utf-8")
    return True


def main(argv: list[str] | None = None) -> int:
    """Generate the region or fail read-only when ``--check`` detects drift."""
    parser = argparse.ArgumentParser()
    parser.add_argument("--path", type=Path, default=DEFAULT_SUPPORT_MATRIX)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)

    if args.check:
        errors = check_support_matrix(args.path)
        if errors:
            for error in errors:
                print(f"ERROR: {error}", file=sys.stderr)
            return 1
        print("Algorithm support matrix is current.")
        return 0

    try:
        changed = write_support_matrix(args.path)
    except SupportMatrixGenerationError as exc:
        print(f"ERROR: {args.path}: {exc}", file=sys.stderr)
        return 1
    print("Updated algorithm support matrix." if changed else "No changes required.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
