"""Shared fail-closed dependency export using the host uv executable."""

from __future__ import annotations

import hashlib
import re
import shutil
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path
from subprocess import CompletedProcess
from typing import Callable, Sequence

LOCAL_REQUIREMENT_PATTERN = re.compile(
    rb"(?im)(?:^|\s)(?:(?:-e|--editable)\s+|file:|/(?!/))"
    rb"|@\s*(?:file:|/|\.\.?/)"
)

CommandRunner = Callable[[Sequence[str], Path], CompletedProcess[str]]


class HostUVExportError(RuntimeError):
    """Raised when host-uv dependency export violates its contract."""


@dataclass(frozen=True)
class HostDependencyExport:
    """Deterministic, hashed requirements generated by host uv."""

    uv_version: str
    content: bytes
    sha256: str


def export_locked_requirements(
    *,
    root: Path,
    extras: Sequence[str],
    baseline_uv_version: str,
    run: CommandRunner,
    warning_prefix: str = "host uv baseline",
) -> HostDependencyExport:
    """Validate the lock and export requirements without host paths."""
    uv = shutil.which("uv")
    if uv is None:
        raise HostUVExportError(
            "uv is required on the host to export locked requirements"
        )

    version_result = run([uv, "--version"], root)
    version_match = re.match(r"^uv\s+(\S+)", version_result.stdout.strip())
    if version_match is None:
        raise HostUVExportError(
            f"unable to determine the host uv version: {version_result.stdout!r}"
        )
    actual_version = version_match.group(1)
    if actual_version != baseline_uv_version:
        print(
            f"WARNING: {warning_prefix} {baseline_uv_version}; detected "
            f"uv {actual_version}. Continuing with locked export.",
            file=sys.stderr,
            flush=True,
        )

    lock_path = root / "uv.lock"
    try:
        lock_before = hashlib.sha256(lock_path.read_bytes()).hexdigest()
    except OSError as exc:
        raise HostUVExportError(f"cannot read lock file: {lock_path}") from exc

    content: bytes | None = None
    try:
        run([uv, "lock", "--check"], root)
        with tempfile.TemporaryDirectory(prefix="tributo-host-uv-export-") as directory:
            output = Path(directory) / "requirements.txt"
            command = [
                uv,
                "export",
                "--format",
                "requirements.txt",
                "--locked",
                "--no-emit-project",
                "--no-default-groups",
                "--no-annotate",
                "--no-header",
            ]
            for extra in extras:
                command.extend(("--extra", str(extra)))
            command.extend(("--output-file", str(output)))
            run(command, root)
            content = output.read_bytes()
    finally:
        try:
            lock_after = hashlib.sha256(lock_path.read_bytes()).hexdigest()
        except OSError as exc:
            raise HostUVExportError(f"cannot reread lock file: {lock_path}") from exc
        if lock_after != lock_before:
            raise HostUVExportError("host uv changed uv.lock during locked export")

    if not content or b"--hash=sha256:" not in content:
        raise HostUVExportError("host uv export must contain hashed requirements")
    root_bytes = str(root.resolve()).encode("utf-8")
    if root_bytes in content or LOCAL_REQUIREMENT_PATTERN.search(content):
        raise HostUVExportError(
            "host uv export must not include the Tributo project or host paths"
        )
    return HostDependencyExport(
        uv_version=actual_version,
        content=content,
        sha256=hashlib.sha256(content).hexdigest(),
    )
