"""Shared import and distribution contract for the Tributo runtime image."""

from __future__ import annotations

REQUIRED_IMPORTS = (
    "tributo.data",
    "tributo.algorithms",
    "tributo.training",
    "tributo.exporting",
    "tributo.inference",
    "tributo.serving",
    "tributo.streaming",
    "tributo.vector_index",
    "tributo.explainability",
    "tributo.registry",
    "tributo.pipeline",
    "daft",
    "ray_hive",
    "lance_ray",
    "lance",
    "pyiceberg",
    "torch",
    "xgboost",
    "onnx",
    "onnxruntime",
    "transformers",
    "shap",
    "mlflow",
    "grpc",
    "confluent_kafka",
    "torch_geometric",
    "daft_clickhouse",
    "daft_doris",
    "ray_doris",
)

REQUIRED_DISTRIBUTIONS = (
    "ray",
    "ray-hive",
    "tributo",
    "daft",
    "lance-ray",
    "pylance",
    "pyiceberg",
    "torch",
    "xgboost",
    "onnx",
    "onnxruntime",
    "transformers",
    "shap",
    "mlflow",
    "grpcio",
    "confluent-kafka",
    "torch-geometric",
    "dowhy",
    "econml",
    "bayesian-optimization",
    "daft-clickhouse",
    "daft-doris",
    "ray-doris",
    "clickhouse-connect",
    "PyMySQL",
    "thrift",
    "adbc-driver-manager",
    "adbc-driver-flightsql",
)

REQUIRED_DISTRIBUTION_VERSIONS = {
    "ray-hive": "1.0",
    "daft-clickhouse": "1.0",
    "daft-doris": "1.0",
    "ray-doris": "1.0",
    "thrift": "0.24.0",
}
