# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tributo/serving/proto/inference.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'tributo/serving/proto/inference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%tributo/serving/proto/inference.proto\x12\x0ftributo.serving\"v\n\x0bInputTensor\x12\x16\n\x0eschema_version\x18\x05 \x01(\x05\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05shape\x18\x02 \x03(\x05\x12\x10\n\x08\x64\x61tatype\x18\x03 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x04 \x03(\x01\x12\x12\n\nint64_data\x18\x06 \x03(\x03\"d\n\x0ePredictRequest\x12,\n\x06inputs\x18\x03 \x03(\x0b\x32\x1c.tributo.serving.InputTensor\x12\x10\n\x08\x66\x65\x61tures\x18\x01 \x03(\x02\x12\x12\n\nmodel_name\x18\x02 \x01(\t\":\n\x0fPredictResponse\x12\x13\n\x0bpredictions\x18\x01 \x03(\x02\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x32\x8b\x02\n\x10InferenceService\x12L\n\x07Predict\x12\x1f.tributo.serving.PredictRequest\x1a .tributo.serving.PredictResponse\x12T\n\rStreamPredict\x12\x1f.tributo.serving.PredictRequest\x1a .tributo.serving.PredictResponse0\x01\x12S\n\x0c\x42\x61tchPredict\x12\x1f.tributo.serving.PredictRequest\x1a .tributo.serving.PredictResponse(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tributo.serving.proto.inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INPUTTENSOR']._serialized_start=58
  _globals['_INPUTTENSOR']._serialized_end=176
  _globals['_PREDICTREQUEST']._serialized_start=178
  _globals['_PREDICTREQUEST']._serialized_end=278
  _globals['_PREDICTRESPONSE']._serialized_start=280
  _globals['_PREDICTRESPONSE']._serialized_end=338
  _globals['_INFERENCESERVICE']._serialized_start=341
  _globals['_INFERENCESERVICE']._serialized_end=608
# @@protoc_insertion_point(module_scope)
