name: Release Drafter

on:
  push:
    branches: [master]
  pull_request_target:
    types: [opened, reopened, synchronize]

permissions:
  contents: read

jobs:
  update-draft-release:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@246878a94cb0e795d863c2de806b0752cde1480f
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
