name: Release Drafter

on:
  push:
    branches: [master]
  pull_request_target:
    types: [opened, reopened, synchronize]

permissions:
  contents: read

jobs:
  update-draft-release:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@f259c0ada5376557cd49e74487398301fab5287a
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
